name: Hugging Push
description: GitHub action that'll push files of the current github code repository to the hugging face space code repository.
author: backendcloud
branding:
  icon: refresh-cw
  color: green

inputs:
  github_repo_id:
    required: true
    type: string
  huggingface_repo_id:
    required: true
    type: string
  hf_token:
    required: true
  repo_type:
    type: string
    default: 'space'
  space_sdk:
    type: string
    default: 'gradio'
  private:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
#    - name: Checkout Action GitHub Repo
#      uses: actions/checkout@v2
#      with:
#        repository: ${{ github.action_repository }}
#        ref: main/${{ github.action_ref }}
#        path: ${{ github.action_repository }}

    - name: Checkout current Repo
      uses: actions/checkout@v2

    - name: Push to Hugging Face
      shell: bash
      run: |
        cd ${{ github.action_path }}
        pip install -r requirements.txt
        cd ~
        pwd
        pwd
        pwd
        python ${{ github.action_path }}/push.py \
          --repo_id ${{ inputs.huggingface_repo_id }} \
          --github_repo ${{ github.repository }} \
          --token ${{ inputs.hf_token }} \
          --repo_type ${{ inputs.repo_type }} \
          --space_sdk ${{ inputs.space_sdk }} \
          --private ${{ inputs.private }}